version: "3.7"
services:
  petclinic:
    build:
      context: ../petclinic/
      dockerfile: ../petclinic/Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic
    depends_on:
      - db
    deploy:
      replicas: 5
      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - petclinic-net

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - petclinic-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - petclinic
    networks:
      - petclinic-net

volumes:
  db_data:

networks:
  petclinic-net:
