version: "3.7"
services:
    # Petclinic Service
    petclinic:
        build:
            context: ../eighth-task
            dockerfile: Dockerfile
        container_name: petclinic
        restart: always
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=mysql
            - MYSQL_URL=jdbc:mysql://db:3306/petclinic
            - MYSQL_USER=petclinic
            - MYSQL_PASS=petclinic
        depends_on:
            - db

    db:
        image: mysql:8.4
        container_name: db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_USER=petclinic
            - MYSQL_PASSWORD=petclinic
            - MYSQL_DATABASE=petclinic
        ports:
            - "3306"
        volumes:
            - "./conf.d:/etc/mysql/conf.d:ro"

volumes:
    db_data: